#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-httr2
Version  : 0.2.3
Release  : 5
URL      : https://cran.r-project.org/src/contrib/httr2_0.2.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/httr2_0.2.3.tar.gz
Summary  : Perform HTTP Requests and Process the Responses
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-cli
Requires: R-curl
Requires: R-glue
Requires: R-magrittr
Requires: R-openssl
Requires: R-rappdirs
Requires: R-rlang
Requires: R-withr
BuildRequires : R-R6
BuildRequires : R-cli
BuildRequires : R-curl
BuildRequires : R-glue
BuildRequires : R-magrittr
BuildRequires : R-openssl
BuildRequires : R-rappdirs
BuildRequires : R-rlang
BuildRequires : R-withr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
performing them and processing the results. 'httr2' is a modern
    re-imagining of 'httr' that uses a pipe-based interface and solves
    more of the problems that API wrapping packages face.

%prep
%setup -q -n httr2
pushd ..
cp -a httr2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683579708

%install
export SOURCE_DATE_EPOCH=1683579708
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/httr2/DESCRIPTION
/usr/lib64/R/library/httr2/INDEX
/usr/lib64/R/library/httr2/LICENSE
/usr/lib64/R/library/httr2/Meta/Rd.rds
/usr/lib64/R/library/httr2/Meta/features.rds
/usr/lib64/R/library/httr2/Meta/hsearch.rds
/usr/lib64/R/library/httr2/Meta/links.rds
/usr/lib64/R/library/httr2/Meta/nsInfo.rds
/usr/lib64/R/library/httr2/Meta/package.rds
/usr/lib64/R/library/httr2/Meta/vignette.rds
/usr/lib64/R/library/httr2/NAMESPACE
/usr/lib64/R/library/httr2/NEWS.md
/usr/lib64/R/library/httr2/R/httr2
/usr/lib64/R/library/httr2/R/httr2.rdb
/usr/lib64/R/library/httr2/R/httr2.rdx
/usr/lib64/R/library/httr2/R/sysdata.rdb
/usr/lib64/R/library/httr2/R/sysdata.rdx
/usr/lib64/R/library/httr2/doc/httr2.R
/usr/lib64/R/library/httr2/doc/httr2.Rmd
/usr/lib64/R/library/httr2/doc/httr2.html
/usr/lib64/R/library/httr2/doc/index.html
/usr/lib64/R/library/httr2/help/AnIndex
/usr/lib64/R/library/httr2/help/aliases.rds
/usr/lib64/R/library/httr2/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/httr2/help/httr2.rdb
/usr/lib64/R/library/httr2/help/httr2.rdx
/usr/lib64/R/library/httr2/help/paths.rds
/usr/lib64/R/library/httr2/html/00Index.html
/usr/lib64/R/library/httr2/html/R.css
/usr/lib64/R/library/httr2/tests/testthat.R
/usr/lib64/R/library/httr2/tests/testthat/_snaps/curl.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/headers.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-client.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-token.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-body.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-cache.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-error.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-options.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-perform.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-template.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-url.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp-body.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp-status.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/secret.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/url.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/httr2/tests/testthat/azure-cert.rds
/usr/lib64/R/library/httr2/tests/testthat/azure-key.rds
/usr/lib64/R/library/httr2/tests/testthat/test-curl.R
/usr/lib64/R/library/httr2/tests/testthat/test-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-multi-req.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-client.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-jwt-google.rds
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-jwt.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-refresh.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-token.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth.R
/usr/lib64/R/library/httr2/tests/testthat/test-parse.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-auth.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-body.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-cache.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-error.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-method.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-mock.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-options.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-perform.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-retries.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-template.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-throttle.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-url.R
/usr/lib64/R/library/httr2/tests/testthat/test-req.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-body.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-status.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp.R
/usr/lib64/R/library/httr2/tests/testthat/test-secret.R
/usr/lib64/R/library/httr2/tests/testthat/test-url.R
/usr/lib64/R/library/httr2/tests/testthat/test-utils.R
