#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-httr2
Version  : 1.0.3
Release  : 11
URL      : https://cran.r-project.org/src/contrib/httr2_1.0.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/httr2_1.0.3.tar.gz
Summary  : Perform HTTP Requests and Process the Responses
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-cli
Requires: R-curl
Requires: R-glue
Requires: R-lifecycle
Requires: R-magrittr
Requires: R-openssl
Requires: R-rappdirs
Requires: R-rlang
Requires: R-vctrs
Requires: R-withr
BuildRequires : R-R6
BuildRequires : R-cli
BuildRequires : R-curl
BuildRequires : R-glue
BuildRequires : R-lifecycle
BuildRequires : R-magrittr
BuildRequires : R-openssl
BuildRequires : R-rappdirs
BuildRequires : R-rlang
BuildRequires : R-vctrs
BuildRequires : R-withr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
performing them and processing the results. 'httr2' is a modern
    re-imagining of 'httr' that uses a pipe-based interface and solves
    more of the problems that API wrapping packages face.

%prep
%setup -q -n httr2
pushd ..
cp -a httr2 buildavx2
popd
pushd ..
cp -a httr2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724328105

%install
export SOURCE_DATE_EPOCH=1724328105
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/httr2/DESCRIPTION
/usr/lib64/R/library/httr2/INDEX
/usr/lib64/R/library/httr2/LICENSE
/usr/lib64/R/library/httr2/Meta/Rd.rds
/usr/lib64/R/library/httr2/Meta/features.rds
/usr/lib64/R/library/httr2/Meta/hsearch.rds
/usr/lib64/R/library/httr2/Meta/links.rds
/usr/lib64/R/library/httr2/Meta/nsInfo.rds
/usr/lib64/R/library/httr2/Meta/package.rds
/usr/lib64/R/library/httr2/Meta/vignette.rds
/usr/lib64/R/library/httr2/NAMESPACE
/usr/lib64/R/library/httr2/NEWS.md
/usr/lib64/R/library/httr2/R/httr2
/usr/lib64/R/library/httr2/R/httr2.rdb
/usr/lib64/R/library/httr2/R/httr2.rdx
/usr/lib64/R/library/httr2/R/sysdata.rdb
/usr/lib64/R/library/httr2/R/sysdata.rdx
/usr/lib64/R/library/httr2/doc/httr2.R
/usr/lib64/R/library/httr2/doc/httr2.Rmd
/usr/lib64/R/library/httr2/doc/httr2.html
/usr/lib64/R/library/httr2/doc/index.html
/usr/lib64/R/library/httr2/help/AnIndex
/usr/lib64/R/library/httr2/help/aliases.rds
/usr/lib64/R/library/httr2/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/httr2/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/httr2/help/figures/logo.png
/usr/lib64/R/library/httr2/help/httr2.rdb
/usr/lib64/R/library/httr2/help/httr2.rdx
/usr/lib64/R/library/httr2/help/paths.rds
/usr/lib64/R/library/httr2/html/00Index.html
/usr/lib64/R/library/httr2/html/R.css
/usr/lib64/R/library/httr2/tests/testthat.R
/usr/lib64/R/library/httr2/tests/testthat/_snaps/content-type.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/curl.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/headers.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/iterate-helpers.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/iterate.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/multi-req.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-client.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-flow-auth-code.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-flow-jwt.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-flow-refresh.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-flow.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth-token.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/oauth.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-body.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-cache.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-cookies.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-error.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-headers.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-mock.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-options.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-perform-stream.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-perform.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-policy.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-retries.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-template.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req-url.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/req.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp-body.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp-status.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/resp.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/secret.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/sequential.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/url.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/utils-multi.md
/usr/lib64/R/library/httr2/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/httr2/tests/testthat/azure-cert.rds
/usr/lib64/R/library/httr2/tests/testthat/azure-key.rds
/usr/lib64/R/library/httr2/tests/testthat/test-content-type.R
/usr/lib64/R/library/httr2/tests/testthat/test-curl.R
/usr/lib64/R/library/httr2/tests/testthat/test-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-iterate-helpers.R
/usr/lib64/R/library/httr2/tests/testthat/test-iterate-responses.R
/usr/lib64/R/library/httr2/tests/testthat/test-iterate.R
/usr/lib64/R/library/httr2/tests/testthat/test-multi-req.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-client.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-auth-code.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-jwt-google.rds
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-jwt.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow-refresh.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-flow.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth-token.R
/usr/lib64/R/library/httr2/tests/testthat/test-oauth.R
/usr/lib64/R/library/httr2/tests/testthat/test-parse.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-auth.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-body.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-cache.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-cookies.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-error.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-method.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-mock.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-options.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-perform-stream.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-perform.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-policy.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-promise.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-retries.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-template.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-throttle.R
/usr/lib64/R/library/httr2/tests/testthat/test-req-url.R
/usr/lib64/R/library/httr2/tests/testthat/test-req.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-body.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-headers.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-status.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp-url.R
/usr/lib64/R/library/httr2/tests/testthat/test-resp.R
/usr/lib64/R/library/httr2/tests/testthat/test-secret.R
/usr/lib64/R/library/httr2/tests/testthat/test-sequential.R
/usr/lib64/R/library/httr2/tests/testthat/test-url.R
/usr/lib64/R/library/httr2/tests/testthat/test-utils-multi.R
/usr/lib64/R/library/httr2/tests/testthat/test-utils.R
